
// Game theme styles
 const styles = {
  container: {
    minHeight: "100vh",
    background:
      "linear-gradient(135deg, #1a0a0a 0%, #2a1515 30%, #1a0a0a 60%, #0f0f1a 100%)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "20px",
  },
  wrapper: {
    width: "100%",
    maxWidth: 650,
    margin: "0 auto",
    animation: "fadeIn 0.5s ease-in-out",
  },
  // Decorative border for game feel
  decorativeBorder: {
    border: "2px solid #D4AF37",
    borderRadius: "20px",
    padding: "4px",
    background: "linear-gradient(135deg, #D4AF37, #B8860B)",
    boxShadow: "0 0 40px rgba(212, 175, 55, 0.2)",
  },
  card: {
    borderRadius: "18px",
    background: "linear-gradient(180deg, #0a0a1a, #1a0a0a)",
    padding: "32px",
    border: "1px solid rgba(212, 175, 55, 0.3)",
  },
  title: {
    textAlign: "center" as const,
    marginBottom: "24px",
  },
  titleIcon: {
    fontSize: "48px",
    display: "block",
    marginBottom: "8px",
  },
  titleMain: {
    color: "#FFD700",
    fontSize: "28px",
    fontWeight: "bold",
    fontFamily: '"Cinzel", "Times New Roman", serif',
    letterSpacing: "4px",
    textShadow: "0 0 30px rgba(255, 215, 0, 0.15)",
  },
  titleSub: {
    color: "#B8860B",
    fontSize: "14px",
    fontFamily: '"Cinzel", "Times New Roman", serif',
    letterSpacing: "2px",
    marginTop: "4px",
  },
  formGroup: {
    marginBottom: "20px",
  },
  label: {
    display: "block",
    color: "#D4AF37",
    fontSize: "14px",
    fontWeight: "600",
    fontFamily: '"Cinzel", "Times New Roman", serif',
    marginBottom: "6px",
    letterSpacing: "1px",
  },
  input: {
    width: "100%",
    padding: "12px 16px",
    background: "rgba(255, 255, 255, 0.05)",
    border: "2px solid rgba(212, 175, 55, 0.3)",
    borderRadius: "12px",
    color: "#D4AF37",
    fontSize: "16px",
    fontFamily: '"Cinzel", "Times New Roman", serif',
    transition: "all 0.3s ease",
    outline: "none",
  },
  inputFocus: {
    borderColor: "#FFD700",
    boxShadow: "0 0 20px rgba(255, 215, 0, 0.1)",
    background: "rgba(255, 255, 255, 0.08)",
  },
  amountPresets: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(80px, 1fr))",
    gap: "8px",
    marginBottom: "12px",
  },
  presetButton: {
    padding: "8px 12px",
    background: "rgba(255, 255, 255, 0.05)",
    border: "2px solid rgba(212, 175, 55, 0.3)",
    borderRadius: "10px",
    color: "#D4AF37",
    fontSize: "13px",
    fontFamily: '"Cinzel", "Times New Roman", serif',
    cursor: "pointer",
    transition: "all 0.3s ease",
    textAlign: "center" as const,
    fontWeight: "600",
  },
  presetButtonActive: {
    background: "rgba(212, 175, 55, 0.2)",
    borderColor: "#FFD700",
    boxShadow: "0 0 20px rgba(255, 215, 0, 0.1)",
    color: "#FFD700",
  },
  customToggle: {
    padding: "8px 16px",
    background: "rgba(255, 255, 255, 0.05)",
    border: "2px dashed rgba(212, 175, 55, 0.3)",
    borderRadius: "10px",
    color: "#B8860B",
    fontSize: "13px",
    fontFamily: '"Cinzel", "Times New Roman", serif',
    cursor: "pointer",
    transition: "all 0.3s ease",
    textAlign: "center" as const,
  },
  customToggleActive: {
    borderColor: "#FFD700",
    color: "#FFD700",
    background: "rgba(212, 175, 55, 0.1)",
  },
  amountDisplay: {
    padding: "12px 16px",
    background: "rgba(212, 175, 55, 0.05)",
    border: "1px solid rgba(212, 175, 55, 0.2)",
    borderRadius: "12px",
    textAlign: "center" as const,
    marginTop: "12px",
  },
  amountText: {
    color: "#B8860B",
    fontSize: "14px",
    fontFamily: '"Cinzel", "Times New Roman", serif',
  },
  amountValue: {
    color: "#FFD700",
    fontSize: "28px",
    fontWeight: "bold",
    fontFamily: '"Cinzel", "Times New Roman", serif',
    textShadow: "0 0 30px rgba(255, 215, 0, 0.1)",
  },
  paymentMethods: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "10px",
  },
  methodButton: {
    padding: "12px",
    background: "rgba(255, 255, 255, 0.05)",
    border: "2px solid rgba(212, 175, 55, 0.2)",
    borderRadius: "12px",
    color: "#D4AF37",
    cursor: "pointer",
    transition: "all 0.3s ease",
    textAlign: "center" as const,
    fontFamily: '"Cinzel", "Times New Roman", serif',
    fontSize: "13px",
  },
  methodButtonActive: {
    background: "rgba(212, 175, 55, 0.15)",
    borderColor: "#FFD700",
    boxShadow: "0 0 20px rgba(255, 215, 0, 0.1)",
    color: "#FFD700",
  },
  methodIcon: {
    fontSize: "24px",
    display: "block",
    marginBottom: "4px",
  },
  submitButton: {
    width: "100%",
    padding: "16px",
    background: "linear-gradient(135deg, #8B0000, #660000)",
    border: "2px solid #D4AF37",
    borderRadius: "14px",
    color: "#FFD700",
    fontSize: "18px",
    fontWeight: "bold",
    fontFamily: '"Cinzel", "Times New Roman", serif',
    cursor: "pointer",
    transition: "all 0.3s ease",
    letterSpacing: "2px",
    boxShadow: "0 4px 20px rgba(139, 0, 0, 0.3)",
    marginTop: "8px",
  },
  submitButtonHover: {
    transform: "translateY(-2px)",
    boxShadow: "0 6px 30px rgba(139, 0, 0, 0.4)",
    background: "linear-gradient(135deg, #A52A2A, #8B0000)",
  },
  cancelButton: {
    width: "100%",
    padding: "14px",
    background: "transparent",
    border: "2px solid rgba(212, 175, 55, 0.3)",
    borderRadius: "14px",
    color: "#B8860B",
    fontSize: "14px",
    fontFamily: '"Cinzel", "Times New Roman", serif',
    cursor: "pointer",
    transition: "all 0.3s ease",
    letterSpacing: "1px",
    marginTop: "8px",
  },
  support: {
    textAlign: "center" as const,
    marginTop: "20px",
    padding: "12px",
    borderTop: "1px solid rgba(212, 175, 55, 0.1)",
    color: "#B8860B",
    fontSize: "12px",
    fontFamily: '"Cinzel", "Times New Roman", serif',
  },
  errorMessage: {
    color: "#FF4444",
    fontSize: "13px",
    fontFamily: '"Cinzel", "Times New Roman", serif',
    marginTop: "4px",
    padding: "8px 12px",
    background: "rgba(255, 68, 68, 0.1)",
    borderRadius: "8px",
    border: "1px solid rgba(255, 68, 68, 0.2)",
  },
};

export   {styles}
