import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import '@ant-design/v5-patch-for-react-19';
import LayoutClient from "@/components/layouts/LayoutClient";
import StoreProvider from "@/lib/redux/StoreProvider";
import { ReactNode } from "react";
const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "12 sứ quân",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: ReactNode;
}>) {

    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`} suppressHydrationWarning
            >
                <StoreProvider>
                    <LayoutClient>
                        {children}
                    </LayoutClient>
                </StoreProvider>
            </body>
        </html>
    );
}
